sudo: required
services:
  - docker

before_install:
  - docker build -t emmalanda2011/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true emmalanda2011/docker-react npm run test
